export const MAP_CONFIG = {
  DEFAULT_ZOOM: 16,
  MIN_ZOOM: 13,
  MAX_ZOOM: 17,
  FLY_DURATION: 1.5,
  TILE_SIZE: 500,
};

export const GPS_CONFIG = {
  CAPTURE_ACCURACY_THRESHOLD: 50,
  HIGH_ACCURACY_THRESHOLD: 15,
  GOOD_ACCURACY_THRESHOLD: 40,
};

export const CAPTURE_CONFIG = {
  EMPTY_TILE_DURATION: 10000,
  ENEMY_TILE_DURATION: 60000,
};
