export const MAP_CONFIG = {
  DEFAULT_ZOOM: 13,
  MIN_ZOOM: 10,
  MAX_ZOOM: 15,
  FLY_DURATION: 1.5,
  TILE_SIZE: 400,
};

export const GPS_CONFIG = {
  CAPTURE_ACCURACY_THRESHOLD: 50,
  HIGH_ACCURACY_THRESHOLD: 15,
  GOOD_ACCURACY_THRESHOLD: 40,
  UNSTABLE_ACCURACY_THRESHOLD: 100,
};

export const CAPTURE_CONFIG = {
  EMPTY_TILE_DURATION: 10000,
  ENEMY_TILE_DURATION: 60000,
};
